spring:
  datasource:
    password: 1
    url: jdbc:oracle:thin:@192.168.3.6:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: pay_lhc170119
    openMulti: false
    type: com.alibaba.druid.pool.DruidDataSource
    idle-timeout: 30000
    validationQuery: SELECT 1 from dual
    initialSize: 5
    maxActive: 20
    maxWait: 60000
    poolMaximumIdleConnections: 0
    poolPreparedStatements: false
    xaDataSourceClassName: com.alibaba.druid.pool.xa.DruidXADataSource
    multi:
    - key: 2017
      password: 1
      url: jdbc:oracle:thin:@192.168.3.6:1521:orcl
      idle-timeout: 20000
      driver-class-name: oracle.jdbc.OracleDriver
      username: pay_lhc170119
      type: com.alibaba.druid.pool.DruidDataSource
    - key: 2017
      password: 1
      url: jdbc:oracle:thin:@192.168.3.6:1521:orcl
      driver-class-name: oracle.jdbc.OracleDriver
      username: pay_lhc170119